image: mhadhbixissam/ubuntu:min

tasks:
  - init: |
      code-server /root/wrokspace 
    command: |
      uvicorn main:app --reload

ports:
  - port: 6080
    onOpen: open-preview
  - port: 6081
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode

