markdown_extensions:
- attr_list
- md_in_html
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    linenums: true
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
nav:
- Tags: Tags.md
- Watershed Algorithm: Watershed_Algorithm.md
- index: index.md
- Hacks:
  - Imshow Matplotlib: Hacks/Imshow_Matplotlib.md
  - Kill Process By Port: Hacks/Kill_Process_By_Port.md
  - Nice bash Couse: Hacks/Nice_bash_Couse.md
  - Rename file: Hacks/Rename_file.md
  - Scrcpy app: Hacks/Scrcpy_app.md
  - Usb Tethering: Hacks/Usb_Tethering.md
  - setup jupyter vs code: Hacks/setup_jupyter_vs_code.md
  - vsocde-make-build: Hacks/vsocde-make-build.md
- chp2: chp2.md
- Chaptre 2: Chaptre_2.md
- Tips and Tricks:
  - Test: Tips and Tricks/Test.md
plugins:
- tags:
    listings_map:
      scoped:
        scope: true
    listings_sort_by: '!!python/name:material.plugins.tags.item_url'
    listings_sort_reverse: true
    tags_file: Tags.md
- search:
    pipeline:
    - stemmer
    - stopWordFilter
    - trimmer
site_name: Issam Mhadhbi
theme:
  features:
  - search.share
  - content.code.copy
  - content.code.select
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
